Pay 5797
hmcts/ccpayfr-shared-infrastructure pull request #80
Opened 2022-11-15 22:41 UTC by anshikanigam15

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-11-16 09:56 UTC, anoojhmcts approved these changes

2022-11-18 09:04 UTC, thomast1906 commented on variables.tf
> +  default     = "Premium"
Do you want Premium SKU in all envs? For cost saving, I would only have Premium in Prod/AAT

2022-11-30 09:55 UTC, thomast1906 requested changes
`sku=standard` is not needed, as you have set it as default in the variable

https://github.com/hmcts/ccpayfr-shared-infrastructure/pull/80/files#diff-05b5a57c136b6ff596500bcbfdcff145ef6cddea2a0e86d184d9daa9a65a288eR63

2022-11-30 10:52 UTC, anshikanigam15 commented
> `sku=standard` is not needed, as you have set it as default in the variable
> 
> see here : https://github.com/hmcts/ccpayfr-shared-infrastructure/pull/80/files#diff-05b5a57c136b6ff596500bcbfdcff145ef6cddea2a0e86d184d9daa9a65a288eR63

Removed SKU Standard

2022-11-30 10:59 UTC, thomast1906 approved these changes
Approving for now, depending you may want likes of AAT/perftest to be same as Production.

Feel free to try this to see how it is.

2022-11-30 11:00 UTC, thomast1906 requested changes
Lets hold on this, to discuss which envs we want as premium, I do think perrftest, aat, prod

2022-12-01 10:25 UTC, thomast1906 commented
perftest & AAT you probably want to be Premium as well to align PTL environments

2022-12-01 12:00 UTC, anshikanigam15 commented
> perftest & AAT you probably want to be Premium as well to align PTL environments



> 

Thanks made both of them as premium

2022-12-01 12:59 UTC, merged